### ISSUE TITLE
Auto-rec plugin

### ISSUE THREAD

**Issue by Wazarr94** [xenonsb/Haxball-Room-Extension#11]
Hi, another idea that popped in my head.

A plugin that allows you to record every game you play.

thx

**Comment by xenonsb** [comment]
Hey, thanks for the suggestion - to prevent too many prompts from starting/stopping of games, I've added a hotkey R (in-game) for you to record quickly as of 0.3.1. By default this option is turned off, but feel free to enable it under add-on settings.

**Comment by Wazarr94** [comment]
Nice to see u back.
I think this implementation is the correct way of doing it.

However I can't manage to use it, pressing R does not start recording for me. Any ideas why ?

**Comment by xenonsb** [comment]
Thanks! So far I made the R hotkey work when in-game to prevent the tabbing back-and-forth. I'll need to look into another part of my code to make it work in the room lobby view.

**Comment by xenonsb** [comment]
As of 0.3.4, the R hotkey should work in the room user list view/in-game view. :)
