### ISSUE TITLE
Feature request: AND operator in the search field

### ISSUE THREAD

**Issue by erenseymen** [xenonsb/Haxball-Room-Extension#14]
Search field currently supports OR operator by using + sign. It would be nice to have AND operator too. For example, if "hp power" is entered in the search field, it should filter all rooms with "hp" and "power".

**Comment by xenonsb** [comment]
It is sorta there - for example if we had a list of room names as follows:

- hp power 123
- hp power 456
- hello world
- don't select

If your search term is "hp power+hello", you'll get the first 3 rooms - just that the search terms need to be in the same order. I don't have plans to implement stronger filter logic based on room name outside of this, sorry :(

**Comment by erenseymen** [comment]
If rooms are like below, "hp power+hello" won't filter first 3 items.
hp 123 power
hp 456 power
hello world
don't select

**Comment by xenonsb** [comment]
Actually came up with this on a stray thought - it's coming up.

**Comment by xenonsb** [comment]
Added in 0.3.4 - thanks!
Logic: separate AND keywords using space, OR keywords using +, room limit using /limit

**Comment by erenseymen** [comment]
Thank you very much
