### ISSUE TITLE
Chat transparency

### ISSUE THREAD

**Issue by Leo-MapCreator** [xenonsb/Haxball-Room-Extension#15]
Hi @xenonsb , 
My idea to improve your extension is to have the possibility to change the chat transparency according to what you think is the better for yourself, nowadays we have the possibility to change transparency from 0% to 100% and 50%(i'm guessing), but for me, personaly, something around 75% would be better, so i think if you could choose the number you want could be better
Thanks in advance

**Comment by xenonsb** [comment]
Sorry been out and about on vacation, added the transparency choice in 0.3.1! Thanks for the suggestion :)

**Comment by Leo-MapCreator** [comment]
Thx :)

**Comment by Leo-MapCreator** [comment]
@xenonsb Just to let you know, higher transparecy = less visible, rn it's working the opposite

**Comment by Leo-MapCreator** [comment]
And can you make it like a number that we write, instead of choosing?

**Comment by xenonsb** [comment]
> @xenonsb Just to let you know, higher transparecy = less visible, rn it's working the opposite

Yup - I set it as % opacity, was easier to work with while scripting (sorry ;p)

> And can you make it like a number that we write, instead of choosing?

I'll look into it - the drag bar I have with 10 levels was the quickest implementation I could make without doing error checking.. otherwise I'll have to add a bit more to handle it!

**Comment by Leo-MapCreator** [comment]
Hahaha, it's ok, i know sometimes coding is a bitch
