### ISSUE TITLE
Auto-Join + Room Filter

### ISSUE THREAD

**Issue by Leo-MapCreator** [xenonsb/Haxball-Room-Extension#16]
They don't work together
If you filter a room, the auto-join doesn't work

**Comment by xenonsb** [comment]
I use those 2 together all the time.. I'm just wondering - did you filter out the room that you want to autojoin?

**Comment by Leo-MapCreator** [comment]
I did use, but it wasn't working, not even trying to join, idk

**Comment by xenonsb** [comment]
Wondering if you did this workflow:

1. Filter rooms using some criteria
2. Click to select the room you want to auto-join (presumably full)
3. Press Autojoin - the screen should sorta flicker as it presses the refresh button

Is it at step 3 that it just refuses to try refreshing/joining? :o

**Comment by Leo-MapCreator** [comment]
I used now and it worked 🤔
Didn't change the procedure i was doing or anything

**Comment by xenonsb** [comment]
:p who knows, I don't recall modifying that piece of the code but glad it's working now!
