### ISSUE TITLE
Feature request: Stop auto-join

### ISSUE THREAD

**Issue by Leo-MapCreator** [xenonsb/Haxball-Room-Extension#17]
Rn when you press auto-join, i will stay forever untill you enter the room, but if you want to give-up and join another room you have to reset the haxball page, otherwise the auto-join will kick in forever and you won't be able to check other rooms :/

**Comment by xenonsb** [comment]
Added in 0.3.3 I believe :) also the autojoin button indicates whether it is working on it or not :D thanks!
