### ISSUE TITLE
Option to hide navbar by default

### ISSUE THREAD

**Issue by Wazarr94** [xenonsb/Haxball-Room-Extension#18]
Hello,

Since you're back, I can share the ideas I had in the meantime.

I think the haxball navbar is pointless and should be hidden by default.
It should remain as an option, since some players may be used to it.

I want this because of the annoying scheme that happens to me way too much:
1) Get in a game
2) Hide Chat + Full Screen + put mouse bottom left corner
3) Realize I didn't remove the navbar
4) Enable Chat + Move my mouse to that button and move it back where it was + hide chat again
5) Kicked for AFK (jk)

**Comment by Leo-MapCreator** [comment]
I like the navBar the way it is
Maybe a button to enter fullscreen mode, that hides everything would solve it.

**Comment by xenonsb** [comment]
Design choice - just wanted to keep what was part of haxball.com as-is. For me, the option to hide it is sufficient. One small click of hide navBar at first game + the hide chat won't kill hopefully!

As for the kicked for AFK thing - did you enable the notifications by any chance? It's a half-baked solution, but hopefully it can help you prevent getting kicked for AFK :)
