### ISSUE TITLE
A way to change your extrapolation quickly

### ISSUE THREAD

**Issue by Wazarr94** [xenonsb/Haxball-Room-Extension#19]
I think players could use 2 keys or 2 buttons (or both) to increase and decrease their extrapolation.

Since lag is an important factor to extrapolation value, having an option to change its value quickly is very useful, especially since the command takes like 2 seconds to type when pressing a button takes 0.1s

**Comment by xenonsb** [comment]
I'm thinking about this possibility - perhaps not just for extrapolation, but just chat messages/commands in general.

To do increase/decrease of extrapolation will be a bit more difficult as I'd have to keep track of changes that occur outside of the extension context.. perhaps we can map some "default commands"?

**Comment by kingjasko** [comment]
Something like !0-200 in chat could change extrapolation, I think that'd be the easiest solution where it wouldn't require that much work and it would still be way easier than typing out the whole thing.

**Comment by xenonsb** [comment]
Yup, in light of all your ideas I've added a chat text-expansion macro for 0.3.4. This allows you to setup shortcuts for these commands:

right now as default I have /e1 as /extrapolation 1 - of course you can redefine extra commands!

To access that menu: go to add-on options and press configure shortcuts, thanks!

**Comment by Wazarr94** [comment]
By default, it should be `/e` -> `/extrapolation ` (with a space at the end) so you just have to type `/e80`

thanks for the change very cool
