### ISSUE TITLE
Hiding Chat Button

### ISSUE THREAD

**Issue by Wazarr94** [xenonsb/Haxball-Room-Extension#2]
For serious matches, it may be useful to consider a little ( - ) button to hide the chat and displaying a ( + ) button to expend it back to its original size.

The transparent chat is decent but not perfect for competitive use.

**Comment by xenonsb** [comment]
Hey, thanks for the suggestion. Just wondering for these matches, do you prefer having a hotkey to toggle the chat expansion or just prefer a mouse-toggle only?

**Comment by Wazarr94** [comment]
A key would be better than mouse, but both choices should be available.

I came back just to mention that Real Soccer is kinda unplayable due to the transparent bottom section (the text can hide the ball when you're on the bottom side).

**Comment by xenonsb** [comment]
> A key would be better than mouse, but both choices should be available.
> 
> I came back just to mention that Real Soccer is kinda unplayable due to the transparent bottom section (the text can hide the ball when you're on the bottom side).

I'll look into implementing a hide chat button/hotkey, but for now the latest update should allow you to disable the transparent chat section. Sorry about that.

**Comment by xenonsb** [comment]
0.2.3 - Use mouse to toggle once, then hotkey is just tab to chat as usual; bottom section disappears after you finish sending the message.
