### ISSUE TITLE
"I did in fact lag" button

### ISSUE THREAD

**Issue by Leo-MapCreator** [xenonsb/Haxball-Room-Extension#20]
Sometimes when you are playing and you lag, people tend to not believe you, so i thought about creating a button to send the ping/maxPing/FPS in the chat so they know you are not lying, or maybe an if condition that when ping goes above a pre-set value or you have package loss (AKA red bar in the graph), it indicates somehow, to others, that you lagged.
Is it possible?

Thx in advance.

**Comment by xenonsb** [comment]
Added in 0.4.1 - sorry for the long wait for this feature, hopefully later is better than never :p

**Comment by Leo-MapCreator** [comment]
thx, love you
