### ISSUE TITLE
Save Passwords

### ISSUE THREAD

**Issue by Raamyy** [xenonsb/Haxball-Room-Extension#21]
Currently many headless rooms exist and every room has it own confirmation password and sometimes it is hard to remember, so the extension may store the password and using may be a command or just copy it from the extension will be good i think.

**Comment by xenonsb** [comment]
For 0.3.4, I added chat text-expansion macro. If you "save" your password as in, assigning the macro ".pw" to "!confirm passcode", typing ".pw" into the chat will expand to "!confirm passcode". :)
