### ISSUE TITLE
Double click for ban/kick

### ISSUE THREAD

**Issue by spr1907** [xenonsb/Haxball-Room-Extension#29]
Any way to have this feature for one click? I don't want to click two times.

**Comment by AnddyAnddy** [comment]
This is (very) old but I liked more the simple click than the double so it would be cool if it was an option to make it simple click

**Comment by xenonsb** [comment]
Yup, originally it was single click but deemed too "unsafe", since we have some admins that mis-click them by accident lol :(

Unfortunately for the safety of the mass, we'll keep it as double click.

**Comment by AnddyAnddy** [comment]
Can't you make us have the choice with a setting to toggle simple/double ?
