### ISSUE TITLE
Correct style for settings

### ISSUE THREAD

**Issue by Wazarr94** [xenonsb/Haxball-Room-Extension#3]
As of today, the choice for the plugins is really ugly. Could you do something a "Plugin settings" button like the rest of the buttons and open a menu like the settings menu already there ?

Thanks.

PS : There are also a lot of messages that get prompted in the console, any way to remove it ?
Also, the search feature should not be saved once you refresh the page imo.

**Comment by xenonsb** [comment]
I'm working on a prettier version for the plugin choices - originally this was a smaller pet project with less options, but I see what you mean. It should come in the next version.

As for the console messages, I'll have the bulk of them removed.

The search feature saving the query terms was a design choice - most players I know have a preference for specific room types, so having it filter from the beginning would add convenience. For players who are not looking to join their regular rooms, they can choose to change the search bar - as it is implemented right now.

**Comment by xenonsb** [comment]
0.2.3 - Choice for plugin is now housed neatly in the same spot, with a new menu that opens.

**Comment by Wazarr94** [comment]
The plugin is looking neat now.
@xenonsb An extremely minor change I'm asking, could you add a space between the buttons in the nickname menu ? adding a margin-right of 5px is satisfying i think.

**Comment by xenonsb** [comment]
Space is added in 0.2.4, thanks!
