### ISSUE TITLE
search on countries

### ISSUE THREAD

**Issue by Jackzoooon** [xenonsb/Haxball-Room-Extension#32]
hello, @xenonsb
first of all, I would like to thank you for making the extension
my idea is about countries in haxball I mean if you want  country I need to search on it and get down to find it.
but I have an easier solution it is to add a search tool on countries like what you did to search on rooms.
I hope you like my idea, thanks for reading it.

**Comment by xenonsb** [comment]
Great idea, delayed implementation but update included in 0.4.1 thanks to @HaxMirage :)
