### ISSUE TITLE
Accessing add-on settings in-game

### ISSUE THREAD

**Issue by Wazarr94** [xenonsb/Haxball-Room-Extension#6]
It would be nice being able to access some settings ingame.

For instance, I do not play with the K/B shortcuts, but in the case someone decides to troll the room by flooding and leaving instantly, I'd like to quickly turn it on to ban the troller.

**Comment by xenonsb** [comment]
I'm not sure the value of the kick-ban buttons if you need to first access the settings pane - wouldn't it be just quicker right clicking the user then pressing the kick/ban prompt at that point? You would save a few mouse movements/clicks that way.

The kick/ban buttons should be non-obtrusive enough to keep them on throughout..
