### ISSUE TITLE
Being able to set all hotkeys by yourself

### ISSUE THREAD

**Issue by Wazarr94** [xenonsb/Haxball-Room-Extension#8]
Hello,

just seen the updates, is pretty cool overall.

but i'd like to be able to choose each hotkey for everything:

![image](https://user-images.githubusercontent.com/39807740/61469507-9bb85380-a97f-11e9-880d-f721bd50ab1b.png)

With the cameras appearing if you check the correct add-on setting and the same scrollbar as the haxball one.
I am asking this because i am not able to hide chat using the keys you suggest, and the cameras keys are not where i want them to be.

PS : If you cannot change the cam 1, 2, 3 and 4 , it's fine.
thanks

**Comment by xenonsb** [comment]
Hey! Just wanted to follow up on this - I'm still drawing a bit of a blank trying to make an interface like that for setting keys.

Are you still having difficulties hiding the chat? The hide key should be the one directly below the ESC key.

**Comment by Wazarr94** [comment]
hello, hiding chat is really easy with the ² key. Some inconsistencies when the game is over, but it's something minor

**Comment by xenonsb** [comment]
Yup! Was a design choice, whenever you need to chat (hitting TAB) or go back to game menu, the chat will re-appear. I just wanted to ensure the chat is out of the way during gameplay, not when looking after room options etc :p
